spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 5Rag^ycn
    platform: postgres
  jpa:
    generate-ddl: true
    database: POSTGRESQL
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: bekaforce@gmail.com
    password: fjshysbjoagtpals
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
security:
  jwt:
    token:
      secret-key: jwtapp
      expire-length: 14400000
  require-ssl: true

server-config:
  upload-path:  '${user.dir}/uploads'